insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('Ford_Focus', 'The Ford Focus ST is the perfect example of a fun hatchback with lots of gusto','Ford','Focus ST','2000 Kg','4378mm (L) x 1825mm (W) x 1454mm (H)','The Ford Focus ST is the perfect example of a fun hatchback with lots of gusto', 'Ford', 1000, 24903, 'assets/sporty_cars/20132014_Ford_Focus.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('Mazda_Miata', 'The Mazda Miata has been the epitome of a lightweight roadster for the past quarter century','Mazda','Mazda Miata','2040 Kg','3915mm (L) x 1735mm (W) x 1230mm (H)','The Mazda Miata has been the epitome of a lightweight roadster for the past quarter century', 'Mazda', 1200, 25725, 'assets/sporty_cars/20022006_Mazda_Miata.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('Scion_FR-S', 'Scion may be gone, but they left us with a very well-conceived rear-wheel-drive sport coupe co-developed by Toyota and Subaru','Scion','FR-S','2050 Kg','4240mm (L) x 1775mm (W) x 1285mm (H)','Scion may be gone, but they left us with a very well-conceived rear-wheel-drive sport coupe co-developed by Toyota and Subaru', 'Scion', 1400, 34550, 'assets/sporty_cars/2013-2014_Scion_FRS.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('Subaru_Impreza_WRX', 'The Subaru Impreza WRX is all about pushing your car to the limits - As one of the quickest and best handling compact cars around this little all-wheel-drive road runner evokes images of rally cars endlessly drifting around tight turns and hairpin curves','Subaru','Impreza WRX','2025 Kg','4460mm (L) x 1775mm (W) x 1480mm (H)','If you want to learn how to slide your car sideways, the WRX is the car. With its sporty good looks and cockpit-like interior, this Subaru delivers a performance experience that is as over-the-top as it is unique', 'Subaru', 1040, 43325, 'assets/sporty_cars/20062008_Subaru_Impreza_WRX.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('Volkswagen_GTI', 'This stylish hatchback racer is bold, despite its small size. Not only does it feel stable and solid at highway speeds, the GTI is very well-mannered on the road through virtually any kind of driving','Volkswagen','GTI','1200 kg','4258mm (L) x 1790mm (W) x 1442mm (H)','Embodying German engineering, the GTI touts a combination of responsive handling, civilized ride quality and impressive fuel economy', 'Volkswagen', 100, 665, 'assets/sporty_cars/20082011_Volkwagen_GTI.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('BMW_Z4', 'The BMW Z4 is a two-seat roadster that matches luxury and elegance with lots of sporty attitude','BMW','Z4','2000 Kg','4239mm (L) x 1790mm (W) x 1291mm (H)','The easy-folding hard top on the 2015 BMW Z4 SDrive35i really opens up the spacious cabin to the elements.', 'BMW', 1000, 24903, 'assets/sporty_cars/BMW_Z4.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('Subaru_BRZ', 'The Subaru BRZ is still a two-door coupe, and it still seats four (the backseaters will be comfiest if they’re kid-sized)','Subaru','BRZ','2000 Kg','4378mm (L) x 1825mm (W) x 1454mm (H)','The suspension got some tweaks to help it hug the corners better, and there’s an available performance package that comes with bigger Brembo® brakes for added stopping power, which let you hit the twisties with more confidence', 'Subaru', 1000, 24903, 'assets/sporty_cars/Subaru_BRZ.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('Subaru_WRX', 'The Subaru WRX takes the vision of what usually comprises the best sports cars — two doors, rear-wheel drive, and two passengers – and turns it on its head','Subaru','WRX','2000 Kg','4595mm (L) x 1795mm (W) x 1475mm (H)','WRX retains its precise steering and nimble handling. Its all-wheel drive gives you additional traction that helps to minimize any power loss should you spin the wheels coming out of a turn on slick terrain.', 'Subaru', 1000, 24903, 'assets/sporty_cars/Subaru_WRX.jpg');  

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('Mazda_MX-5_Miata', 'In addition to this sports car low-slung body and sleekly powerful lines, youll like the fact that you can retract the roof at an intersection before the stoplight changes from red to green','Mazda','MX-5 Miata','2000 Kg','3915mm (L) x 1735mm (W) x 1230mm (H)','Rather than stowing completely away, only the rear window and overhead roof panel disappear. It is a classy look for a two-seater. If you have your heart set on a soft top, you can also choose one (as a manually-folding option)', 'Mazda', 1000, 24903, 'assets/sporty_cars/Mazda_MX5_Miata.jpg');  

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('Nissan_370Z', 'If classic sports car styling is what gets your heart racing, the 2017 Nissan 370Z delivers','Nissan','370Z','2000 Kg','4250mm (L) x 1845mm (W) x 1315mm (H)','The coupe and convertible models come standard with a V6 engine thats situated farther back on the car frame', 'Nissan', 1000, 24903, 'assets/sporty_cars/Nissan_370Z.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('Volkswagen_GTI_S', 'Since its introduction to the US market in 1983, the Volkswagen Golf GTI has gained an almost iconic status. It folds sporty styling, a powerful engine, and a generous cargo area into a compact body. A four-door hatchback (two-door GTIs were phased out at the end of the 2016 model year), the 2017 GTI is offered in four trim levels.','Volkswagen','GTI S','2000 Kg','4258mm (L) x 1790mm (W) x 1442mm (H)','As a front-wheel-drive sports car, the 2017 Volkswagen GTI S comes with a 2.0L, turbocharged four-cylinder engine as standard equipment. If you want more horsepower under the hood of this compact powerhouse, choose a Sport, SE, or Autobahn trim level, which bumps your hp to 220.', 'Volkswagen', 1000, 24903, 'assets/sporty_cars/Volkswagen_GTI.jpg');  

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('Chevrolet_Corvette', 'All-American sports car fans can not go wrong with the Chevrolet Corvette. This two-seater, sporty car is available either as a low-slung and graceful coupe or as a convertible. New for 2017 is a Grand Sport trim level that joins the base Stingray, Stingray Z51, and Z06 trim levels','Chevrolet','Corvette','2000 Kg','4378mm (L) x 1825mm (W) x 1454mm (H)','The Chevrolet With its sporty good looks and cockpit-like interior, it delivers a performance experience that is as over-the-top as it is unique', 'Chevrolet', 1000, 24903, 'assets/sporty_cars/Chevrolet_Corvette.jpg');  

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('Mercedes-Benz_AMG_GT_R_Coupe', 'The Mercedes-Benz AMG GT is available as a 2-door, 2-seat coupe','Mercedes-Benz','Mercedes-Benz AMG GT','2000 Kg','4240mm (L) x 1825mm (W) x 1454mm (H)','Starting at $112,400, the 2018 Mercedes-Benz AMG GT Base Coupe is powered by a 4.0L, 8-cylinder engine mated to anautomatic transmission that returns an EPA estimated 16-mpg in the city and 22-mpg on the highway', 'Mercedes-Benz', 1000, 112400, 'assets/sporty_cars/MercedesBenz_AMGGT_R_Coupe.jpg');  

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('Porsche_718_Cayman_GTS', 'The Porsche 718 Cayman is available as a 2-door, 2-seat coupe','Porsche','718 Cayman','2000 Kg','4239mm (L) x 1825mm (W) x 1454mm (H)','Starting at $55,300, the 2018 Porsche 718 Cayman Base is powered by a 2.0L, 4-cylinder engine mated to amanual transmission that returns an EPA estimated 21-mpg in the city and 28-mpg on the highway', 'Porsche', 1000, 24903, 'assets/sporty_cars/Porsche_718_Cayman.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('Honda_Civic_Type_R_Touring', 'The Honda Civic Type R is available as a 4-door, 4-seat hatchback','Honda','Honda Civic Type R','2000 Kg','4378mm (L) x 1825mm (W) x 1454mm (H)','Starting at $34,700, the 2018 Honda Civic Type R Touring is powered by a 2.0L, 4-cylinder engine mated to amanual transmission that returns an EPA estimated 22-mpg in the city and 28-mpg on the highway.', 'Honda', 1000, 24903, 'assets/sporty_cars/Honda_Civic_Type_R.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('Audi_RS_2.5T', 'The Audi RS 3 is available as a 4-door, 5-seat sedan','Audi','Audi RS 3 2.5T','2000 Kg','3915mm (L) x 1825mm (W) x 1454mm (H)','Starting at $54,900, the 2018 Audi RS 3 2.5T is powered by a 2.5L, 5-cylinder engine mated to anautomatic transmission that returns an EPA estimated 19-mpg in the city and 28-mpg on the highway', 'Audi', 1000, 24903, 'assets/sporty_cars/Audi_RS_3_2.5T.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('McLaren_570S_Spider', 'The McLaren Spider is available as a 2-door, 2-seat coupe','McLaren','McLaren Spider','2000 Kg','4250mm (L) x 1825mm (W) x 1454mm (H)','Starting at $112,400, the 2018 McLaren Spider is powered by a 4.0L, 8-cylinder engine mated to anautomatic transmission that returns an EPA estimated 16-mpg in the city and 22-mpg on the highway', 'McLaren', 1000, 24903, 'assets/sporty_cars/McLaren_Spider_5.jpg');  

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('Ford_Focus', 'Turbocharged 2.0 liter Ecoboost engine', '246 horsepower and 250 lb-ft of torque', 'Fast-shifting 6-speed manual transmission','Delivers a very sporty driving experience', 'Focus ST also does well in corners, with lots of grip and balance, invoking a sense of confidence on the curviest of roads','The Focus is also a showcase for all the latest technology');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('Mazda_Miata', 'Turbocharged 2.0 liter Ecoboost engine', '246 horsepower and 250 lb-ft of torque', 'Fast-shifting 6-speed manual transmission','Delivers a very sporty driving experience', 'Mazda Miata also does well in corners, with lots of grip and balance, invoking a sense of confidence on the curviest of roads','The Focus is also a showcase for all the latest technology');    

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('Scion_FR-S', '2.0-liter flat-4 engine channeling 200 hp', '6-speed manual transmission', '6-speed automatic','Lightweight, concise dimensions', 'Low center of gravity ','Balanced chassis');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('Subaru_Impreza_WRX', '2.5-liter 4-cylinder engine', '224 hp', 'Lightening fast reflexes','Slide your car sideways', 'Sporty good looks ','Cockpit-like interior');  

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('Volkswagen_GTI', '2.0-liter inline-4 engine', '200 hp', 'Standard 6-speed manual gearbox','Optional 6-speed dual-clutch automatic', 'Cabin exudes plenty of refinement and high-quality materials','Generous cargo capacity');    

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('BMW_Z4', '2.0-litre four-pot, the turbocharged B58 six cylinder engine', 'Eight-speed auto gearbox', '7000rpm redline','Digital instrument cluster', 'Front-wheel drive architecture','Grille does not have slats but mesh');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('Subaru_BRZ', '2.0L four-cylinder engine ', 'six-speed manual transmission', '60 mph from a stop in just over six seconds (stickshift version)','two-door coupe, and it still seats four (the backseaters will be comfiest if they’re kid-sized)', 'gets an estimated 21 mpg in the city and 29 mpg on the highway','Brembo® brakes for added stopping power, which let you hit the twisties with more confidence');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('Subaru_WRX', 'four-cylinder, turbocharged engine', 'four-door’s six-speed stickshift and nimble handling', 'all-wheel drive gives you additional traction that helps to minimize any power loss should you spin the wheels coming out of a turn on slick terrain','two doors, rear-wheel drive, and two passengers', 'five-passenger sedan','classy look'); 

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('Mazda_MX-5_Miata', '2.0L turbo charged engine', 'Retractable Fastback', 'low-slung body and sleekly powerful lines', 'retract the roof at an intersection before the stoplight changes from red to green','manually-folding option', 'standard 2.0L four-cylinder engine that delivers 155 hp');  

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('Nissan_370Z', 'V6 engine', 'six-speed manual transmission', 'For a bump in horsepower to 350 ponies – as well as some serious racecar looks','more-balanced weight distribution gives it a maneuverability', 'driver and passenger knee airbag','airbag occupancy sensor, automatic air conditioning');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('Volkswagen_GTI_S', '2.5L H-4 365hp intercooled turbo engine', '8-cylinder engine', '7-speed auto-shift manual transmission with overdrive','Integrated navigation system', 'driver and passenger knee airbag','balanced weight distribution gives it a maneuverability');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('Chevrolet_Corvette', '2.5L H-4 365hp intercooled turbo engine', '6-speed manual transmission with overdrive, 4-wheel anti-lock brakes (ABS)', 'Integrated navigation system','SmartVent side seat mounted airbagsr', 'airbag occupancy sensor','driver and passenger knee airbag');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('Mercedes-Benz_AMG_GT_R_Coupe', 'AMG 4.0L V-8 577hp twin turbo engine', '7-speed auto-shift manual transmission with overdrive', '4-wheel anti-lock brakes (ABS)','Integrated navigation system', 'Side seat mounted airbags','Curtain 1st row overhead airbag, driver and passenger knee airbag, airbag occupancy sensor, automatic air conditioning, 19" AMG forged aluminum wheels, cruise control, ABS and driveline traction control');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('Porsche_718_Cayman_GTS', '2.5L H-4 365hp intercooled turbo engine', '6-speed manual transmission with overdrive', '4-wheel anti-lock brakes (ABS)','Side seat mounted airbags', 'Curtain 1st row overhead airbag, driver and passenger knee airbag, airbag occupancy sensor','air conditioning, 20" aluminum wheels, cruise control, ABS and driveline traction control, electronic stability');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('Honda_Civic_Type_R_Touring', '2.0L I-4 306hp intercooled turbo engine', '6-speed manual transmission with overdrive', '4-wheel anti-lock brakes (ABS)','Integrated navigation system', 'SmartVent side seat mounted airbags','curtain 1st and 2nd row overhead airbags, airbag occupancy sensor, automatic air conditioning, 20" aluminum wheels, cruise control, ABS and driveline traction control'); 

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('Audi_RS_2.5T', '2.5L I-5 400hp intercooled turbo engine', '7-speed S tronic auto-shift manual transmission with overdrive', '4-wheel anti-lock brakes (ABS)','side seat mounted airbags, SIDEGUARD curtain 1st and 2nd row overhead airbags, driver and passenger knee airbag, airbag occupancy sensor', 'automatic air conditioning, 19" aluminum wheels, cruise control','ABS and driveline traction control, quattro all-wheel drive');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('McLaren_570S_Spider', '4.0L, 8-cylinder engine', 'anautomatic transmission', 'carbon fiber shell','wonderfully creative and luxurious interior design', 'top speed of 204 mph','0 to 60 capability of 3.1 seconds');   



